### PR TITLE
Drop Python 2.7 support from CI and tox

### PR DESCRIPTION
**Pull request by kalikiana**
Fixes [poo#89206](https://progress.opensuse.org/issues/89206)

### CODE REVIEW

**Review by perlpunk — APPROVED** [review]

**Review by Martchus — APPROVED** [review]
That's basically what I've suggested in the ticket so I'm fine with it.

**Comment by okurz** [comment]
I would be more explicit with dropping python2 support, not just remove it from testing but searching for all relevant references

**Review by okurz — CHANGES_REQUESTED** [review]
(FPL-N525WT-IS
-C25C/M-SDE2E3FGHRWXY/LB1
-EGKK1525
-N0390F240 BOGNA L612 BENBO Y47 DRAKE L151 SITET/N0390F280 UN859 LGL/N0390F180 A34 BOBSA BOBSA6E
-LFPO0115 EBBR
-PBN/A1B2C2D2D3O2O3S2 DOF/210303 REG/N525WT RMK/TCAS)

**Comment by Martchus** [comment]
I wanted to write the same but couldn't find any references to Python 2 in the README.

**Comment by kalikiana** [comment]
The only mentions of it are in the Travis and tox configurations afair

**Comment by okurz** [comment]
well, it's a bit hidden but there, e.g.

* mentions of pip and package names in https://github.com/os-autoinst/openqa_review/blob/master/README.md#usage , probably need to be python3 variants
* https://github.com/os-autoinst/openqa_review/blob/master/setup.py#L12
* https://github.com/os-autoinst/openqa_review/blob/master/setup.py#L45
* https://github.com/os-autoinst/openqa_review/blob/master/openqa_review/openqa_review.py#L90

though all except the first is basically "compatibility code" which doesn't harm, so probably only the first point needs covering

**Comment by okurz** [comment]
tests fail now. As suggested in https://github.com/os-autoinst/openqa_review/pull/140#issuecomment-790040615 please only handle the first point

**Comment by okurz** [comment]
have you seen my suggestion to only focus on "mentions of pip and package names in https://github.com/os-autoinst/openqa_review/blob/master/README.md#usage , probably need to be python3 variants"?

**Comment by kalikiana** [comment]
> have you seen my suggestion to only focus on "mentions of pip and package names in https://github.com/os-autoinst/openqa_review/blob/master/README.md#usage , probably need to be python3 variants"?

Yes. And I was following your suggestion to drop the `FileNotFoundError = IOError` bit. But I'm splitting up the changes now and I would suggest to only keep the tox/ci bits and disambiguate documented commands in this PR.

**Pull request merged**
