### PR TITLE
Consistently use openqa_review from its own installation

### PR DESCRIPTION
**Pull request by kalikiana**
Otherwise we end up trying to run from a git clone and getting some of the code from git and some from what happens to be installed.

See: https://progress.opensuse.org/issues/75214

### CODE REVIEW

**Comment by kalikiana** [comment]
FYI failing on `ImportError: No module named enum`, so blocking on #140

**Review by okurz — CHANGES_REQUESTED** [review]
As the path can already be set with variables you are removing support for running valid applications from default paths which I don't think is a good idea. I don't see the point in keeping this PR open but you can have the decision on that.

**Comment by kalikiana** [comment]
> As the path can already be set with variables you are removing support for running valid applications from default paths which I don't think is a good idea. I don't see the point in keeping this PR open but you can have the decision on that.

The default should be that everything runs from the same codebase, no? Or do you have a different expectation?

**Comment by okurz** [comment]
> The default should be that everything runs from the same codebase, no? Or do you have a different expectation?

I am open to both options but what your change does is to remove support for selecting the application in PATH

**Comment by kalikiana** [comment]
> > The default should be that everything runs from the same codebase, no? Or do you have a different expectation?
> 
> I am open to both options but what your change does is to remove support for selecting the application in PATH

I assume your PATH can include the folder containing the binaries from *openqa_review*. What use case is missing here?

**Comment by okurz** [comment]
Well, when installed the application is called "openqa-review" which does not exist in source files but is generated on installation. But you delete the code that calls "openqa-review".

**Comment by kalikiana** [comment]
> Well, when installed the application is called "openqa-review" which does not exist in source files but is generated on installation. But you delete the code that calls "openqa-review".

I don't get your point. This PR is supposed ensure that openqa_review scripts always use code from the same installation, regardless of wether that's git, pip or rpm.

I'm closing it for now since this was only meant to be a trivial fix.

**Comment by okurz** [comment]
> > Well, when installed the application is called "openqa-review" which does not exist in source files but is generated on installation. But you delete the code that calls "openqa-review".
> 
> I don't get your point. This PR is supposed ensure that openqa_review scripts always use code from the same installation, regardless of wether that's git, pip or rpm.

Yes, but the path `./openqa_review/openqa_review.py` would not be correct depending on the directories where files are installed and by default python packages are installed so that binaries are e.g. within /usr/bin and python files are in /usr/share/… so the relative path would not work anymore.

How about we properly install all necessary scripts as part of the RPM package and use the package consistently without relying on the git checkout?

**Comment by Martchus** [comment]
> without relying on the git checkout?

It would still be good if we keep the use-case of local development in mind. Usually one doesn't want to install binaries during development. Obviously one can just set `OPENQA_REVIEW` for this so maybe it just be documented.

**Pull request closed without merging**
