### PR TITLE
Use black to format and check python code style, 2nd variant

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by mimi1vx** [comment]
tox integration .. nice

line length 160 is too much, black itself has default 88 which is slightly higher than old standard, +- recommended value for line is between 80-120.

btw. flake uses 79 as line length by default  ... if you have 160 it means you manulally set value this vas as example config in flake docs, nothing else

+ we can use `flake8-black` plugin and --> check code format by flake using black as plugin

**Comment by okurz** [comment]
> line length 160 is too much, black itself has default 88 which is slightly higher than old standard, +- recommended value for line is between 80-120.

I know. I like how black explains how that makes sense. But going back now for the current project I consider a bit too much making IMHO too many lines not that readable anymore.

> btw. flake uses 79 as line length by default ... if you have 160 it means you manulally set value this vas as example config in flake docs, nothing else

Not sure what you mean. We had 160 set in tox.ini for flake8

>     * we can use `flake8-black` plugin and --> check code format by flake using black as plugin

ok, nice. I plan to look into this later.

> btw. in perl project we use line length 120 --> maybe using same value across our source code will not be bad idea

Well, actually os-autoinst and hence os-autoinst-distri-opensuse uses a line limit of 160 characters. I introduced that because I thought 160 is better than no limit at all which we had in before but I could not easily convince everybody to go down further in one go.

I have added a commit to use 120

**Comment by okurz** [comment]
@mimi1vx I think I have all your suggestions included now, equivalent to your updates in https://github.com/os-autoinst/openqa_review/pull/142 . I also brought back the complexity check with a simple move of a one-line comment. Are you ok with this PR which also includes the most important parts of your commits?

**Review by Martchus — APPROVED** [review]
So this PR and #142 are apparently about https://progress.opensuse.org/issues/92665. It would be nice to add a ticket reference to the commit messages in the future. Otherwise I'm fine with the PR (but also don't really care about the style here).

**Comment by mimi1vx** [comment]
LGTM, I'll close #142

**Pull request merged**
